RN50: 
  embed_dim : 1024
  image_resolution : 224
  vision_layers : [3, 4, 6, 3]
  vision_width : 64
  vision_patch_size : 0 # ideally it should be none
  context_length : 77
  vocab_size : 49408
  transformer_width : 512
  transformer_heads : 8
  transformer_layers : 6 # 12 in CLIP

ViTL14:
  embed_dim : 768
  image_resolution : 224
  vision_layers : 24
  vision_width : 1024
  vision_patch_size : 14 # ideally it should be none
  context_length : 77
  vocab_size : 49408
  transformer_width : 768
  transformer_heads : 12
  transformer_layers : 12 # 12 in CLIP

ViTB16:
  embed_dim : 512
  image_resolution : 224
  vision_layers : 12
  vision_width : 768
  vision_patch_size : 16 # ideally it should be none
  context_length : 77
  vocab_size : 49408
  transformer_width : 512
  transformer_heads : 8
  transformer_layers : 12 # 12 in CLIP

ViTB32:
  embed_dim : 512
  image_resolution : 224
  vision_layers : 12
  vision_width : 768
  vision_patch_size : 32 # ideally it should be none
  context_length : 77
  vocab_size : 49408
  transformer_width : 512
  transformer_heads : 8
  transformer_layers : 12 # 12 in CLIP

RN50_2048: 
  embed_dim : 1024
  image_resolution : 224
  vision_layers : [3, 4, 6, 3]
  vision_width : 2048
  vision_patch_size : 0 # ideally it should be none
  context_length : 77
  vocab_size : 49408
  transformer_width : 512
  transformer_heads : 8
  transformer_layers : 6 # 12 in CLIP